name: Android_CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-11

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Decode Keystore
        id: write_file
        uses: timheuer/base64-to-file@v1.1
        with:
          fileName: '../WeatherApp/WeatherApp/keystore/weatherApp.jks'
          encodedString: ${{ secrets.KEYSTORE }}

      - name: Build APK release
        run: |
          ./gradlew assembleRelease --stacktrace
        env:
          SIGN_STORE_PASSWORD: ${{ secrets.SIGN_STORE_PASSWORD }}
          SIGN_KEY_PASSWORD: ${{ secrets.SIGN_KEY_PASSWORD }}
          SIGN_KEY_ALIAS: ${{ secrets.SIGN_KEY_ALIAS }}
          API_KEY: ${{ secrets.API_KEY }}

      - name: Build APK debug
        run: ./gradlew assembleDebug --stacktrace
        env:
          API_KEY: ${{ secrets.API_KEY }}

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: weatherApp
          path: app/build/outputs/apk/release/app-release.apk

      - name: Lint check
        run: |
          ./gradlew ktlintCheck
        env:
          API_KEY: ${{ secrets.API_KEY }}

      - name: Unit Test with Android Emulator Runner
        uses: ReactiveCircus/android-emulator-runner@v2.22.0
        with:
          api-level: 29
          script: ./gradlew jacocoTestReport
        env:
          API_KEY: ${{ secrets.API_KEY }}

      - name: generate report
        uses: actions/upload-artifact@v2
        with:
          name: report
          path: app/build/reports/coverage/androidTest/debug


      - name: Download Test Reports Folder
        uses: actions/download-artifact@v2
        with:
          name: report
          path: app/build/reports/coverage/androidTest/debug

      - name: Upload Test Report
        run:  bash <(curl -s https://codecov.io/bash) -f "app/build/reports/coverage/androidTest/debug/report.xml"
#        See code coverage report https://app.codecov.io/gh/IBashniak/WeatherApp/
