name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-11

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
          API_KEYV: ${{ secrets.API_KEY }}

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Lint check
        run: |
          export API_KEY=$API_KEYV
          ./gradlew ktlintCheck

      - name: Unit Test with Android Emulator Runner
        uses: ReactiveCircus/android-emulator-runner@v2.22.0
        with:
          api-level: 29
          script: export API_KEY=$API_KEYV && ./gradlew jacocoTestReport

      - name: generate report
        uses: actions/upload-artifact@v2
        with:
          name: report
          path: app/build/reports/coverage/androidTest/debug


      - name: Download Test Reports Folder
        uses: actions/download-artifact@v2
        with:
          name: report
          path: app/build/reports/coverage/androidTest/debug

      - name: Upload Test Report
        run:  bash <(curl -s https://codecov.io/bash) -f "app/build/reports/coverage/androidTest/debug/report.xml"
#        See code coverage report https://app.codecov.io/gh/IBashniak/WeatherApp/
